services:
  mysql:
    image: mysql:8.0
    container_name: codefolio-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=codefolio123
      - MYSQL_DATABASE=codefolio
      - MYSQL_USER=codefolio
      - MYSQL_PASSWORD=codefolio123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - codefolio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7.0
    container_name: codefolio-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - codefolio-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: codefolio-jaeger
    restart: unless-stopped
    ports:
      - "6831:6831/udp"  # jaeger-agent
      - "6832:6832/udp"  # jaeger-agent
      - "5778:5778"      # jaeger-agent
      - "16686:16686"    # jaeger-query
      - "4317:4317"      # OTLP gRPC
      - "4318:4318"      # OTLP HTTP
      - "14250:14250"    # jaeger-agent
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - jaeger-data:/var/lib/jaeger
    networks:
      - codefolio-network

volumes:
  mysql-data:
  redis-data:
  jaeger-data:

networks:
  codefolio-network:
    driver: bridge