version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    environment:
      - APP_SERVER_PORT=8080
      - APP_STORAGE_TYPE=database
      - APP_STORAGE_DATABASE_HOST=mysql
      - APP_STORAGE_DATABASE_PORT=3306
      - APP_STORAGE_DATABASE_USER=root
      - APP_STORAGE_DATABASE_PASSWORD=your_password
      - APP_STORAGE_DATABASE_DBNAME=codefolio
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=codefolio
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge 