// Package user provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package user

import (
	"encoding/json"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Message *string `json:"message,omitempty"`

	// Token JWT 令牌
	Token *string `json:"token,omitempty"`
}

// Email defines model for Email.
type Email = openapi_types.Email

// EmailPasswordSignin defines model for EmailPasswordSignin.
type EmailPasswordSignin struct {
	Email Email `json:"email"`

	// Password 用户密码，至少 8 位
	Password Password `json:"password"`
}

// Error defines model for Error.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// Password 用户密码，至少 8 位
type Password = string

// RequestSignupCode defines model for RequestSignupCode.
type RequestSignupCode struct {
	Email Email `json:"email"`
}

// UserSignup defines model for UserSignup.
type UserSignup struct {
	Email Email `json:"email"`

	// Password 用户密码，至少 8 位
	Password Password `json:"password"`

	// Username 用户名
	Username Username `json:"username"`
}

// Username 用户名
type Username = string

// VerificationCode 邮箱验证码
type VerificationCode = string

// VerifySignupCode defines model for VerifySignupCode.
type VerifySignupCode struct {
	// Code 邮箱验证码
	Code  VerificationCode `json:"code"`
	Email Email            `json:"email"`
}

// Response defines model for response.
type Response struct {
	Data    map[string]interface{} `json:"data"`
	Errno   int                    `json:"errno"`
	Message string                 `json:"message"`
	TraceId string                 `json:"trace_id"`
}

// PostAuthSigninJSONBody defines parameters for PostAuthSignin.
type PostAuthSigninJSONBody struct {
	union json.RawMessage
}

// PostAuthSignupJSONBody defines parameters for PostAuthSignup.
type PostAuthSignupJSONBody struct {
	union json.RawMessage
}

// PostAuthSigninJSONRequestBody defines body for PostAuthSignin for application/json ContentType.
type PostAuthSigninJSONRequestBody PostAuthSigninJSONBody

// PostAuthSignupJSONRequestBody defines body for PostAuthSignup for application/json ContentType.
type PostAuthSignupJSONRequestBody PostAuthSignupJSONBody
